language: php

dist: trusty

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

before_script:
  - travis_retry composer self-update

script:
  - composer install
  - vendor/bin/phpunit
